services:
  # Backend API Service
  - type: web
    name: rx-assistant-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1

  # Frontend Web Service  
  - type: web
    name: rx-assistant-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: rx-assistant-backend
          property: host